### ISSUE TITLE
Projects support

### ISSUE THREAD

**Issue by lexesv** [visualfc/liteide#841]
Please answer these questions before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?
X32.2

### What version of Go are you using (`go version`)?
1.9

### What operating system and processor architecture are you using(`go env`)?
Linux and 64 QT 4.8.1

Feature request:
Add project support.
For example, the file is an app.lide (yml) that contains a path to the folder with the files, a list of open files and build configuration.
When you open the project file - a new window(!) (or query) is created with open files from config. (All other open tabs are closed)
Thus, many projects can be opened in different windows. This is very convenient, for example, it works in webstorm

Example:
**app.lide (yml)**
```yml
Path: /home/user/dev/go/src/test
OpenFiles:
 - main.go
 - doc.go
BuildConfig: [configuration like Actions, GOPATH, etc...]
```
